#!/bin/bash
#
#PBS -l select=1:ncpus=2:mem=24GB
#PBS -l walltime=8:00:00
#PBS -N LDSC_rg
#PBS -e /home/uqjjian3/jobs_sterr_stout/
#PBS -o /home/uqjjian3/jobs_sterr_stout/
#PBS -A UQ-IMB-CNSG

#######################################################
### This script is used to format the GWAS sumstats and run genetic correlation analysis using LDSC
#######################################################

### "Munge" Data --> formatting the sumstats dataset to suit the LDSC format
### NOTE: Some of these datasets contain UKB individuals and may not be the ones used to generate PRS.

### For CAD
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/munge_sumstats.py \
--sumstats /QRISdata/Q4319/Statin_project_Clara/data/openGWAS/formatted_CAD_VDH_UKB_ebiaGCST005194_N \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_CAD \
--merge-alleles /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/w_hm3.snplist \
--chunksize 500000

### For MD
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/munge_sumstats.py \
--sumstats /QRISdata/Q4319/data/MDD_Howard_2018_no23andme/formatted_PGC_UKB_depression_no23andme \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_MD \
--merge-alleles /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/w_hm3.snplist \
--chunksize 500000

### For BD
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/munge_sumstats.py \
--sumstats /QRISdata/Q4319/data/BIP_Mullins_2021/formatted_BIP_Mullins_2021 \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_BD \
--merge-alleles /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/w_hm3.snplist \
--chunksize 500000

### For SCZ
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/munge_sumstats.py \
--sumstats /QRISdata/Q4319/data/SCZ_Lam_2019/formatted_SCZ_Lam_2019 \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_SCZ \
--merge-alleles /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/w_hm3.snplist \
--chunksize 500000 

### For HF
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/munge_sumstats.py \
--sumstats /QRISdata/Q4319/data/HF_Shah_2020/formatted_HF_Shah_2020 \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_HF \
--merge-alleles /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/w_hm3.snplist \
--chunksize 500000 

### For AF
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/munge_sumstats.py \
--sumstats /QRISdata/Q4319/data/AF_Nielsen_2018/formatted_AF_Nielsen_2018 \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_AF \
--merge-alleles /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/w_hm3.snplist \
--chunksize 500000 

#######################################################

### Calculating genetic correlation between Psyc and CVD traits

### AF_MD_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_AF.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_MD.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/AF_MD_ldsc_rg

### AF_BD_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_AF.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_BD.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/AF_BD_ldsc_rg

### AF_SCZ_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_AF.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_SCZ.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/AF_SCZ_ldsc_rg

### CAD_MD_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_CAD.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_MD.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/CAD_MD_ldsc_rg

### CAD_BD_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_CAD.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_BD.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/CAD_BD_ldsc_rg

### CAD_SCZ_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_CAD.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_SCZ.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/CAD_SCZ_ldsc_rg

### HF_MD_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_HF.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_MD.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/HF_MD_ldsc_rg

### HF_BD_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_HF.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_BD.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/HF_BD_ldsc_rg

### HF_SCZ_ldsc_rg
/home/uqjjian3/anaconda3/envs/ldsc/bin/python2.7 /home/uqjjian3/utils/LDSC/ldsc/ldsc.py \
--rg /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_HF.sumstats.gz,/scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/ldsc_formatted_SCZ.sumstats.gz \
--ref-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--w-ld-chr /home/uqjjian3/utils/LDSC/LD_scores/eur_w_ld_chr/ \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/1_LDSC_genetic_correlation/HF_SCZ_ldsc_rg


