#!/bin/bash
#
#PBS -l select=1:ncpus=8:mem=50GB
#PBS -l walltime=72:00:00
#PBS -N BD_bi
#PBS -e /home/uqjjian3/jobs_sterr_stout/
#PBS -o /home/uqjjian3/jobs_sterr_stout/
#PBS -A UQ-IMB-CNSG
#PBS -J 1-20

#########################################
### Fitting bivariate model for BD and CAD
#########################################
### Fitting the bivariate fast model
/home/uqjjian3/utils/conda_utils/bin/python3.8 /home/uqjjian3/utils/MiXer/mixer/precimed/mixer.py fit2 \
--trait1-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_BD_z_noMHC.csv.gz \
--trait2-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_CAD_z_noMHC.csv.gz \
--trait1-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_univariate_fit1/BD_univariate/mixer_formatted_BD_z_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--trait2-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_univariate_fit1/CAD_univariate/mixer_formatted_CAD_z_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_CAD_noMHC.fit.rep${PBS_ARRAY_INDEX} \
--extract /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep${PBS_ARRAY_INDEX}.snps \
--bim-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib  /home/uqjjian3/utils/MiXer/mixer/src/build/lib/libbgmg.so \
--threads 8

### Fitting the bivariate full model
/home/uqjjian3/utils/conda_utils/bin/python3.8 /home/uqjjian3/utils/MiXer/mixer/precimed/mixer.py test2 \
--trait1-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_BD_z_noMHC.csv.gz \
--trait2-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_CAD_z_noMHC.csv.gz \
--load-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_CAD_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_CAD_noMHC.test.rep${PBS_ARRAY_INDEX} \
--bim-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib  /home/uqjjian3/utils/MiXer/mixer/src/build/lib/libbgmg.so \
--threads 8

#########################################
### Fitting bivariate model for BD and HF
#########################################
### Fitting the bivariate fast model
/home/uqjjian3/utils/conda_utils/bin/python3.8 /home/uqjjian3/utils/MiXer/mixer/precimed/mixer.py fit2 \
--trait1-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_BD_z_noMHC.csv.gz \
--trait2-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_HF_z_noMHC.csv.gz \
--trait1-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_univariate_fit1/BD_univariate/mixer_formatted_BD_z_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--trait2-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_univariate_fit1/HF_univariate/mixer_formatted_HF_z_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_HF_noMHC.fit.rep${PBS_ARRAY_INDEX} \
--extract /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep${PBS_ARRAY_INDEX}.snps \
--bim-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib  /home/uqjjian3/utils/MiXer/mixer/src/build/lib/libbgmg.so \
--threads 8

### Fitting the bivariate full model
/home/uqjjian3/utils/conda_utils/bin/python3.8 /home/uqjjian3/utils/MiXer/mixer/precimed/mixer.py test2 \
--trait1-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_BD_z_noMHC.csv.gz \
--trait2-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_HF_z_noMHC.csv.gz \
--load-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_HF_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_HF_noMHC.test.rep${PBS_ARRAY_INDEX} \
--bim-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib  /home/uqjjian3/utils/MiXer/mixer/src/build/lib/libbgmg.so \
--threads 8

#########################################
### Fitting bivariate model for BD and AF
#########################################
### Fitting the bivariate fast model
/home/uqjjian3/utils/conda_utils/bin/python3.8 /home/uqjjian3/utils/MiXer/mixer/precimed/mixer.py fit2 \
--trait1-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_BD_z_noMHC.csv.gz \
--trait2-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_AF_z_noMHC.csv.gz \
--trait1-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_univariate_fit1/BD_univariate/mixer_formatted_BD_z_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--trait2-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_univariate_fit1/AF_univariate/mixer_formatted_AF_z_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_AF_noMHC.fit.rep${PBS_ARRAY_INDEX} \
--extract /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.prune_maf0p05_rand2M_r2p8.rep${PBS_ARRAY_INDEX}.snps \
--bim-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib  /home/uqjjian3/utils/MiXer/mixer/src/build/lib/libbgmg.so \
--threads 8

### Fitting the bivariate full model
/home/uqjjian3/utils/conda_utils/bin/python3.8 /home/uqjjian3/utils/MiXer/mixer/precimed/mixer.py test2 \
--trait1-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_BD_z_noMHC.csv.gz \
--trait2-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_formatting_noMHC/mixer_formatted_AF_z_noMHC.csv.gz \
--load-params-file /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_AF_noMHC.fit.rep${PBS_ARRAY_INDEX}.json \
--out /scratch/user/uqjjian3/CVD_Psych_PRS_project/63_checkpoint_24Aug2022/2_MiXer_polygenic_overlap/MiXer_bivariate_fit2/BD_bivariate/BD_vs_AF_noMHC.test.rep${PBS_ARRAY_INDEX} \
--bim-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.bim \
--ld-file /QRISdata/Q4319/utils/MiXer/LD_reference/1000G_EUR_Phase3_plink/1000G.EUR.QC.@.run4.ld \
--lib  /home/uqjjian3/utils/MiXer/mixer/src/build/lib/libbgmg.so \
--threads 8
